class Constant:
    MAX_BUFFER_SIZE = 1024
    MAX_CHAR_NUM = 50
    FLOW_INTERVAL = 10000
    USER_TIMEOUT = 60
    RECV_TIMEOUT = 5
    SELECT_TIMEOUT = 0.5

    LOCATOR = "01111110"
    TRANSFORM_TARGET = "11111"
    ACK = "Y"
    NAK = "N"
    EMPTY_FRAME = "0" * 88
    BROADCAST_PORT = 65535

    BITS_PER_CHAR = 16
    HOST_PER_SWITCHER = 2
    SWITCHER_PER_ROUTER = 2
    BROADCAST_RECVER_NUM = 3
    LOCATOR_LEN = 8
    PORT_LEN = 8
    SEQ_LEN = 8
    CHECKSUM_LEN = 8
    DATA_LEN = 8

    RECV = 1
    UNICAST = 2
    BROADCAST = 3
    QUIT = 4
